status: unstable
context:
  sizes:
    - identifier: "$j-size-0-25"
      value: 0.25
    - identifier: "$j-size-0-5"
      value: 0.5
    - identifier: "$j-size-0-75"
      value: 0.75
    - identifier: "$j-size-1"
      value: 1
    - identifier: "$j-size-1-5"
      value: 1.5
    - identifier: "$j-size-2"
      value: 2
    - identifier: "$j-size-3"
      value: 3
    - identifier: "$j-size-4"
      value: 4
    - identifier: "$j-size-6"
      value: 6
    - identifier: "$j-size-8"
      value: 8
    - identifier: "$j-size-12"
      value: 12
    - identifier: "$j-size-16"
      value: 16
    - identifier: "$j-size-24"
      value: 24
    - identifier: "$j-size-32"
      value: 32
    - identifier: "$j-size-40"
      value: 40
    - identifier: "$j-size-48"
      value: 48
    - identifier: "$j-size-56"
      value: 56
    - identifier: "$j-size-64"
      value: 64
