status: unstable
context:
  label: This is an input
  placeholder: This is an input...
  modifier: null
variants:
  - name: "Error"
    context:
      modifier: error
      error: There is a problem with this value.