/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JButton {
        "styling"?: ButtonStyling;
    }
    interface JContentSection {
    }
    interface JProse {
    }
}
declare global {
    interface HTMLJButtonElement extends Components.JButton, HTMLStencilElement {
    }
    var HTMLJButtonElement: {
        prototype: HTMLJButtonElement;
        new (): HTMLJButtonElement;
    };
    interface HTMLJContentSectionElement extends Components.JContentSection, HTMLStencilElement {
    }
    var HTMLJContentSectionElement: {
        prototype: HTMLJContentSectionElement;
        new (): HTMLJContentSectionElement;
    };
    interface HTMLJProseElement extends Components.JProse, HTMLStencilElement {
    }
    var HTMLJProseElement: {
        prototype: HTMLJProseElement;
        new (): HTMLJProseElement;
    };
    interface HTMLElementTagNameMap {
        "j-button": HTMLJButtonElement;
        "j-content-section": HTMLJContentSectionElement;
        "j-prose": HTMLJProseElement;
    }
}
declare namespace LocalJSX {
    interface JButton {
        "styling"?: ButtonStyling;
    }
    interface JContentSection {
    }
    interface JProse {
    }
    interface IntrinsicElements {
        "j-button": JButton;
        "j-content-section": JContentSection;
        "j-prose": JProse;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "j-button": LocalJSX.JButton & JSXBase.HTMLAttributes<HTMLJButtonElement>;
            "j-content-section": LocalJSX.JContentSection & JSXBase.HTMLAttributes<HTMLJContentSectionElement>;
            "j-prose": LocalJSX.JProse & JSXBase.HTMLAttributes<HTMLJProseElement>;
        }
    }
}
