/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JContentSection {
    }
    interface JProse {
    }
    interface MyComponent {
        /**
          * The name
         */
        "name": string;
    }
}
declare global {
    interface HTMLJContentSectionElement extends Components.JContentSection, HTMLStencilElement {
    }
    var HTMLJContentSectionElement: {
        prototype: HTMLJContentSectionElement;
        new (): HTMLJContentSectionElement;
    };
    interface HTMLJProseElement extends Components.JProse, HTMLStencilElement {
    }
    var HTMLJProseElement: {
        prototype: HTMLJProseElement;
        new (): HTMLJProseElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "j-content-section": HTMLJContentSectionElement;
        "j-prose": HTMLJProseElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface JContentSection {
    }
    interface JProse {
    }
    interface MyComponent {
        /**
          * The name
         */
        "name"?: string;
    }
    interface IntrinsicElements {
        "j-content-section": JContentSection;
        "j-prose": JProse;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "j-content-section": LocalJSX.JContentSection & JSXBase.HTMLAttributes<HTMLJContentSectionElement>;
            "j-prose": LocalJSX.JProse & JSXBase.HTMLAttributes<HTMLJProseElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
