status: unstable
context:
  colours:
    - name: "Teal"
      shades:
        - identifier: "$j-c-teal-300"
          value: "#3da9a0"
        - identifier: "$j-c-teal-400"
          value: "#259f94"
        - identifier: "$j-c-teal-500"
          value: "#0d9488"
        - identifier: "$j-c-teal-600"
          value: "#0c857a"
        - identifier: "$j-c-teal-700"
          value: "#0a766d"
        - identifier: "$j-c-teal-800"
          value: "#09685f"
    - name: "Atom"
      shades:
        - identifier: "$j-c-atom-50"
          value: "#353f4e"
        - identifier: "$j-c-atom-100"
          value: "#323a47"
        - identifier: "$j-c-atom-200"
          value: "#2e3541"
        - identifier: "$j-c-atom-300"
          value: "#2b303b"
        - identifier: "$j-c-atom-400"
          value: "#272B34"
        - identifier: "$j-c-atom-500"
          value: "#242830"
        - identifier: "$j-c-atom-600"
          value: "#21252d"
        - identifier: "$j-c-atom-700"
          value: "#1e2229"
        - identifier: "$j-c-atom-800"
          value: "#1b1f26"
        - identifier: "$j-c-atom-900"
          value: "#16191e"
    - name: "Mono"
      shades:
        - identifier: "$j-c-blueGrey-50"
          value: "#a9b4c5"
        - identifier: "$j-c-blueGrey-100"
          value: "#9ca7b8"
        - identifier: "$j-c-blueGrey-200"
          value: "#909bab"
        - identifier: "$j-c-blueGrey-300"
          value: "#838e9f"
        - identifier: "$j-c-blueGrey-400"
          value: "#778192"
        - identifier: "$j-c-blueGrey-500"
          value: "#6a7585"
        - identifier: "$j-c-blueGrey-600"
          value: "#5e6878"
        - identifier: "$j-c-blueGrey-700"
          value: "#515b6c"
        - identifier: "$j-c-blueGrey-800"
          value: "#454f5f"
        - identifier: "$j-c-blueGrey-900"
          value: "#374151"
    - name: "Mono"
      shades:
        - identifier: "$j-c-mono-50"
          value: "#fff"
        - identifier: "$j-c-mono-100"
          value: "#eee"
        - identifier: "$j-c-mono-200"
          value: "#ccc"
        - identifier: "$j-c-mono-300"
          value: "#aaa"
        - identifier: "$j-c-mono-400"
          value: "#666"
        - identifier: "$j-c-mono-500"
          value: "#444"
        - identifier: "$j-c-mono-600"
          value: "#333"
        - identifier: "$j-c-mono-700"
          value: "#222"
        - identifier: "$j-c-mono-800"
          value: "#1a1a1a"
        - identifier: "$j-c-mono-900"
          value: "#111"
    - name: "Red"
      shades:
        - identifier: "$j-c-red-200"
          value: "#ec8585"
        - identifier: "$j-c-red-300"
          value: "#e55c5c"
        - identifier: "$j-c-red-400"
          value: "#e24747"
        - identifier: "$j-c-red-500"
          value: "#df3333"
        - identifier: "$j-c-red-600"
          value: "#c92e2e"
        - identifier: "$j-c-red-700"
          value: "#b22929"
    - name: "Green"
      shades:
        - identifier: "$j-c-green-200"
          value: "#8bb694"
        - identifier: "$j-c-green-300"
          value: "#649d71"
        - identifier: "$j-c-green-400"
          value: "#50915f"
        - identifier: "$j-c-green-500"
          value: "#3d854d"
        - identifier: "$j-c-green-600"
          value: "#377845"
        - identifier: "$j-c-green-700"
          value: "#316a3e"
    - name: "Orange"
      shades:
        - identifier: "$j-c-orange-200"
          value: "#edad80"
        - identifier: "$j-c-orange-300"
          value: "#e79155"
        - identifier: "$j-c-orange-400"
          value: "#e48440"
        - identifier: "$j-c-orange-500"
          value: "#e1762b"
        - identifier: "$j-c-orange-600"
          value: "#cb6a27"
        - identifier: "$j-c-orange-700"
          value: "#b45e22"
    - name: "Yellow"
      shades:
        - identifier: "$j-c-yellow-200"
          value: "#fdd97c"
        - identifier: "$j-c-yellow-300"
          value: '#fccc50'
        - identifier: "$j-c-yellow-400"
          value: "#fbc53a"
        - identifier: "$j-c-yellow-500"
          value: "#FBBF24"
        - identifier: "$j-c-yellow-600"
          value: "#e2ac20"
        - identifier: "$j-c-yellow-700"
          value: "#c9991d"
    - name: "Blue"
      shades:
        - identifier: "$j-c-blue-200"
          value: "#76b2d0"
        - identifier: "$j-c-blue-300"
          value: '#4998c0'
        - identifier: "$j-c-blue-400"
          value: "#328bb8"
        - identifier: "$j-c-blue-500"
          value: "#1B7EB0"
        - identifier: "$j-c-blue-600"
          value: "#18719e"
        - identifier: "$j-c-blue-700"
          value: "#16658d"
    - name: "Purple"
      shades:
        - identifier: "$j-c-purple-200"
          value: "#b69eeb"
        - identifier: "$j-c-purple-300"
          value: '#9d7ee5'
        - identifier: "$j-c-purple-400"
          value: "#916ee1"
        - identifier: "$j-c-purple-500"
          value: "#855ede"
        - identifier: "$j-c-purple-600"
          value: "#7855c8"
        - identifier: "$j-c-purple-700"
          value: "#6a4bb2"
    - name: "Pink"
      shades:
        - identifier: "$j-c-pink-200"
          value: "#e281b1"
        - identifier: "$j-c-pink-300"
          value: '#d85797'
        - identifier: "$j-c-pink-400"
          value: "#d3428a"
        - identifier: "$j-c-pink-500"
          value: "#CE2D7D"
        - identifier: "$j-c-pink-600"
          value: "#b92971"
        - identifier: "$j-c-pink-700"
          value: "#a52464"